TARGET := iphone:clang:16.5:16.0
INSTALL_TARGET_PROCESSES = SpringBoard

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Gestures16

Gestures16_FILES = Tweak.x
Gestures16_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
